/Users/vladimirkopylov/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/price_bot/price_bot.py", line 4, in <module>
    bot = telebot.TeleBot(TOKEN)
  File "/Users/vladimirkopylov/Library/Python/3.9/lib/python/site-packages/telebot/__init__.py", line 196, in __init__
    util.validate_token(self.token)
  File "/Users/vladimirkopylov/Library/Python/3.9/lib/python/site-packages/telebot/util.py", line 695, in validate_token
    raise ValueError('Token must contain a colon')
ValueError: Token must contain a colon
